// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: favorites/favorites.proto

package favorites

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FavoriteItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComicId       int32                  `protobuf:"varint,1,opt,name=comic_id,json=comicId,proto3" json:"comic_id,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,2,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteItem) Reset() {
	*x = FavoriteItem{}
	mi := &file_favorites_favorites_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteItem) ProtoMessage() {}

func (x *FavoriteItem) ProtoReflect() protoreflect.Message {
	mi := &file_favorites_favorites_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteItem.ProtoReflect.Descriptor instead.
func (*FavoriteItem) Descriptor() ([]byte, []int) {
	return file_favorites_favorites_proto_rawDescGZIP(), []int{0}
}

func (x *FavoriteItem) GetComicId() int32 {
	if x != nil {
		return x.ComicId
	}
	return 0
}

func (x *FavoriteItem) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FavoriteItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_favorites_favorites_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_favorites_favorites_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_favorites_favorites_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetItems() []*FavoriteItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ComicId       int32                  `protobuf:"varint,2,opt,name=comic_id,json=comicId,proto3" json:"comic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_favorites_favorites_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_favorites_favorites_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_favorites_favorites_proto_rawDescGZIP(), []int{2}
}

func (x *AddRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddRequest) GetComicId() int32 {
	if x != nil {
		return x.ComicId
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ComicId       int32                  `protobuf:"varint,2,opt,name=comic_id,json=comicId,proto3" json:"comic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_favorites_favorites_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_favorites_favorites_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_favorites_favorites_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteRequest) GetComicId() int32 {
	if x != nil {
		return x.ComicId
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_favorites_favorites_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_favorites_favorites_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_favorites_favorites_proto_rawDescGZIP(), []int{4}
}

func (x *ListRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_favorites_favorites_proto protoreflect.FileDescriptor

const file_favorites_favorites_proto_rawDesc = "" +
	"\n" +
	"\x19favorites/favorites.proto\x12\tfavorites\x1a\x1bgoogle/protobuf/empty.proto\"Q\n" +
	"\fFavoriteItem\x12\x19\n" +
	"\bcomic_id\x18\x01 \x01(\x05R\acomicId\x12&\n" +
	"\x0fcreated_at_unix\x18\x02 \x01(\x03R\rcreatedAtUnix\"=\n" +
	"\fListResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.favorites.FavoriteItemR\x05items\"@\n" +
	"\n" +
	"AddRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x19\n" +
	"\bcomic_id\x18\x02 \x01(\x05R\acomicId\"C\n" +
	"\rDeleteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x19\n" +
	"\bcomic_id\x18\x02 \x01(\x05R\acomicId\"&\n" +
	"\vListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId2\xee\x01\n" +
	"\tFavorites\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x124\n" +
	"\x03Add\x12\x15.favorites.AddRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\x06Delete\x12\x18.favorites.DeleteRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x04List\x12\x16.favorites.ListRequest\x1a\x17.favorites.ListResponseB\"Z yadro.com/course/proto/favoritesb\x06proto3"

var (
	file_favorites_favorites_proto_rawDescOnce sync.Once
	file_favorites_favorites_proto_rawDescData []byte
)

func file_favorites_favorites_proto_rawDescGZIP() []byte {
	file_favorites_favorites_proto_rawDescOnce.Do(func() {
		file_favorites_favorites_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_favorites_favorites_proto_rawDesc), len(file_favorites_favorites_proto_rawDesc)))
	})
	return file_favorites_favorites_proto_rawDescData
}

var file_favorites_favorites_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_favorites_favorites_proto_goTypes = []any{
	(*FavoriteItem)(nil),  // 0: favorites.FavoriteItem
	(*ListResponse)(nil),  // 1: favorites.ListResponse
	(*AddRequest)(nil),    // 2: favorites.AddRequest
	(*DeleteRequest)(nil), // 3: favorites.DeleteRequest
	(*ListRequest)(nil),   // 4: favorites.ListRequest
	(*emptypb.Empty)(nil), // 5: google.protobuf.Empty
}
var file_favorites_favorites_proto_depIdxs = []int32{
	0, // 0: favorites.ListResponse.items:type_name -> favorites.FavoriteItem
	5, // 1: favorites.Favorites.Ping:input_type -> google.protobuf.Empty
	2, // 2: favorites.Favorites.Add:input_type -> favorites.AddRequest
	3, // 3: favorites.Favorites.Delete:input_type -> favorites.DeleteRequest
	4, // 4: favorites.Favorites.List:input_type -> favorites.ListRequest
	5, // 5: favorites.Favorites.Ping:output_type -> google.protobuf.Empty
	5, // 6: favorites.Favorites.Add:output_type -> google.protobuf.Empty
	5, // 7: favorites.Favorites.Delete:output_type -> google.protobuf.Empty
	1, // 8: favorites.Favorites.List:output_type -> favorites.ListResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_favorites_favorites_proto_init() }
func file_favorites_favorites_proto_init() {
	if File_favorites_favorites_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_favorites_favorites_proto_rawDesc), len(file_favorites_favorites_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_favorites_favorites_proto_goTypes,
		DependencyIndexes: file_favorites_favorites_proto_depIdxs,
		MessageInfos:      file_favorites_favorites_proto_msgTypes,
	}.Build()
	File_favorites_favorites_proto = out.File
	file_favorites_favorites_proto_goTypes = nil
	file_favorites_favorites_proto_depIdxs = nil
}
