// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: search/search.proto

package search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phrase        string                 `protobuf:"bytes,1,opt,name=phrase,proto3" json:"phrase,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetPhrase() string {
	if x != nil {
		return x.Phrase
	}
	return ""
}

func (x *SearchRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ComicReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComicReply) Reset() {
	*x = ComicReply{}
	mi := &file_search_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComicReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComicReply) ProtoMessage() {}

func (x *ComicReply) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComicReply.ProtoReflect.Descriptor instead.
func (*ComicReply) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{1}
}

func (x *ComicReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ComicReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SearchReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comics        []*ComicReply          `protobuf:"bytes,1,rep,name=comics,proto3" json:"comics,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReply) Reset() {
	*x = SearchReply{}
	mi := &file_search_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReply) ProtoMessage() {}

func (x *SearchReply) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReply.ProtoReflect.Descriptor instead.
func (*SearchReply) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchReply) GetComics() []*ComicReply {
	if x != nil {
		return x.Comics
	}
	return nil
}

func (x *SearchReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_search_search_proto protoreflect.FileDescriptor

const file_search_search_proto_rawDesc = "" +
	"\n" +
	"\x13search/search.proto\x12\x06search\x1a\x1bgoogle/protobuf/empty.proto\"=\n" +
	"\rSearchRequest\x12\x16\n" +
	"\x06phrase\x18\x01 \x01(\tR\x06phrase\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\".\n" +
	"\n" +
	"ComicReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"O\n" +
	"\vSearchReply\x12*\n" +
	"\x06comics\x18\x01 \x03(\v2\x12.search.ComicReplyR\x06comics\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total2\xb1\x01\n" +
	"\x06Search\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x122\n" +
	"\x04Find\x12\x15.search.SearchRequest\x1a\x13.search.SearchReply\x12;\n" +
	"\rIndexedSearch\x12\x15.search.SearchRequest\x1a\x13.search.SearchReplyB\x1fZ\x1dyadro.com/course/proto/searchb\x06proto3"

var (
	file_search_search_proto_rawDescOnce sync.Once
	file_search_search_proto_rawDescData []byte
)

func file_search_search_proto_rawDescGZIP() []byte {
	file_search_search_proto_rawDescOnce.Do(func() {
		file_search_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_search_proto_rawDesc), len(file_search_search_proto_rawDesc)))
	})
	return file_search_search_proto_rawDescData
}

var file_search_search_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_search_search_proto_goTypes = []any{
	(*SearchRequest)(nil), // 0: search.SearchRequest
	(*ComicReply)(nil),    // 1: search.ComicReply
	(*SearchReply)(nil),   // 2: search.SearchReply
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_search_search_proto_depIdxs = []int32{
	1, // 0: search.SearchReply.comics:type_name -> search.ComicReply
	3, // 1: search.Search.Ping:input_type -> google.protobuf.Empty
	0, // 2: search.Search.Find:input_type -> search.SearchRequest
	0, // 3: search.Search.IndexedSearch:input_type -> search.SearchRequest
	3, // 4: search.Search.Ping:output_type -> google.protobuf.Empty
	2, // 5: search.Search.Find:output_type -> search.SearchReply
	2, // 6: search.Search.IndexedSearch:output_type -> search.SearchReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_search_search_proto_init() }
func file_search_search_proto_init() {
	if File_search_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_search_proto_rawDesc), len(file_search_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_search_proto_goTypes,
		DependencyIndexes: file_search_search_proto_depIdxs,
		MessageInfos:      file_search_search_proto_msgTypes,
	}.Build()
	File_search_search_proto = out.File
	file_search_search_proto_goTypes = nil
	file_search_search_proto_depIdxs = nil
}
